# Generated by Django 3.2.8 on 2021-10-13 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LSM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 4, 10, 19, 473149, tzinfo=utc)),
        ),
    ]
